### ISSUE TITLE
Stray .dockerenv causes unexpected behaviour in software

### ISSUE THREAD

**Issue by LLBlumire** [vineelsai26/Arch-WSL#10]
Because of the `.dockerenv` in the filesystem root, software can incorrect believe itself to be in a docker environment. If this is not needed, it should be removed, or if possible renamed to avoid this behavior. 

Details can be seen here: https://github.com/starship/starship/issues/3862

**Comment by vineelsai26** [comment]
Fixed it will be in the next release but it won't affect existing installs so you need to delete it on your own in your existing install
