### ISSUE TITLE
Profile for Windows Terminal 

### ISSUE THREAD

**Issue by timhagel** [vineelsai26/Arch-WSL#8]
How can I add a profile tab for arch to my windows terminal?

**Comment by vineelsai26** [comment]
It should auto-add WSL to the windows terminal once you set up the username and password If not add this to your terminal config

```
{
    "guid": "{a5a97cb8-8961-5535-816d-772efe0c6a3f}",
    "hidden": false,
    "icon": "D:\\GoogleDrive\\Pictures\\Logos\\Arch.png",
    "name": "Arch",
    "source": "Windows.Terminal.Wsl",
    "tabTitle": "Arch"
},
```

**Comment by timhagel** [comment]
> It should auto-add WSL to the windows terminal once you set up the username and password If not add this to your terminal config
> 
> ```
> {
>     "guid": "{a5a97cb8-8961-5535-816d-772efe0c6a3f}",
>     "hidden": false,
>     "icon": "D:\\GoogleDrive\\Pictures\\Logos\\Arch.png",
>     "name": "Arch",
>     "source": "Windows.Terminal.Wsl",
>     "tabTitle": "Arch"
> },
> ```

Thank you so much... this worked
